[package]
name = "player-list"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arcdps = { git = "https://github.com/zerthox/arcdps-bindings", features = ["extras"] }
once_cell = "1.18.0"
toml = "0.7.6"

[lib]
crate-type = ["cdylib"]
